version: '3.7'
services:
    app:
        build:
            args:
                user: ${USER}
                uid: 1000
            context: ./
            dockerfile: ./.docker/php/Dockerfile
        image: reborn
        container_name: reborn-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - reborn
    db:
        image: mysql:5.7
        container_name: reborn-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: reborn
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./.docker/mysql:/docker-entrypoint-initdb.d
            - ./.docker/mysql/database.sql:/docker-entrypoint-initdb.d/db.sql
        networks:
            - reborn
    mailhog:
        image: mailhog/mailhog
        logging:
            driver: 'none'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - reborn
    nginx:
        image: nginx:alpine
        container_name: reborn-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/
            - ./.docker/nginx:/etc/nginx/conf.d/
        networks:
            - reborn
networks:
    reborn:
        driver: bridge
